const searchSugests: any = [
   {
      id: "1",
      title: "آموزش جاوا اسکریپت",
      link: "/search/1?title=آموزش جاوا اسکریپت",
      categoryTitle: "مقاله",
      visitNumber: 1300,
      history: true,
   },
   {
      id: 2,
      title: "آموزش جاوا",
      link: "/search/1?title=آموزش جاوا",
      categoryTitle: "مقاله",
      visitNumber: 650,
      history: false,
   },
   {
      id: 3,
      title: "آموزش تایپ اسکریپت",
      link: "/search/1?title=آموزش تایپ اسکریپت",
      categoryTitle: "ویدیو آموزشی",
      visitNumber: 505,
      history: true,
   },
   {
      id: 4,
      title: "آموزش سی شارپ",
      link: "/search/1?title=آموزش سی شارپ",
      categoryTitle: "ویدیو آموزشی",
      visitNumber: 200,
      history: false,
   },
   {
      id: 5,
      title: "آموزش پایتون",
      link: "/search/1?title=آموزش پایتون ",
      categoryTitle: "ویدیو آموزشی",
      visitNumber: 680,
      history: false,
   },
   {
      id: 6,
      title: "آموزش html",
      link: "/search/1?title=آموزش html ",
      categoryTitle: "مقاله",
      visitNumber: 650,
      history: false,
   },
   {
      id: 7,
      title: "آموزش css",
      link: "/search/1?title=آموزش css ",
      categoryTitle: "ویدیو آموزشی",
      visitNumber: 82,
      history: true,
   },
   {
      id: 8,
      title: "آموزش tailwind",
      link: "/search/1?title=آموزش tailwind ",
      categoryTitle: "مقاله",
      visitNumber: 505,
      history: false,
   },
   {
      id: 9,
      title: "آموزش sass",
      link: "/search/1?title=آموزش sass ",
      categoryTitle: "مقاله",
      visitNumber: 505,
      history: true,
   },
   {
      id: 10,
      title: "react",
      link: "/search/1?title=آموزش react ",
      categoryTitle: "ویدیو آموزشی",
      visitNumber: 505,
      history: false,
   },
   {
      id: 11,
      title: "redux",
      link: "/search/1?title=آموزش redux ",
      categoryTitle: "مقاله",
      visitNumber: 505,
      history: false,
   },
   {
      id: 12,
      title: "آموزش react hooks",
      link: "/search/1?title=آموزش react hooks ",
      categoryTitle: "ویدیو آموزشی",
      visitNumber: 505,
      history: true,
   },
   {
      id: 13,
      title: "git",
      link: "/search/1?title=آموزش git ",
      categoryTitle: "مقاله",
      visitNumber: 505,
      history: false,
   },
   {
      id: 14,
      title: "item1",
      link: "/search/1?title=item1",
      categoryTitle: "مقاله",
      visitNumber: 505,
      history: false,
   },
   {
      id: 15,
      title: "item2",
      link: "/search/1?title=item2",
      categoryTitle: "ویدیو آموزشی",
      visitNumber: 505,
      history: true,
   },
   {
      id: 16,
      title: "item3",
      link: "/search/1?title=item3 ",
      categoryTitle: "ویدیو آموزشی",
      visitNumber: 505,
      history: false,
   },
   {
      id: 17,
      title: "item4",
      link: "/search/1?title= item4 ",
      categoryTitle: "مقاله",
      visitNumber: 505,
      history: false,
   },
   {
      id: 18,
      title: "item5",
      link: "/search/1?title= item5 ",
      categoryTitle: "ویدیو آموزشی",
      visitNumber: 505,
      history: false,
   },
   {
      id: 19,
      title: "Mehran jamali",
      link: "/search/1?title= Mehran jamali",
      categoryTitle: "نویسنده",
      visitNumber: 600,
      history: true,
   },
   {
      id: 20,
      title: "john Doe",
      link: "/search/1?title=john Doe",
      categoryTitle: "نویسنده",
      visitNumber: 700,
      history: false,
   },
];

export const getAllSugests = () => {
   return searchSugests;
};
